# 脚本功能：伴学课堂
# >口语星球
^https?:\/\/api\.banxueketang\.com\/api\/classpal\/app\/v1 url script-response-body https://raw.githubusercontent.com/WeiGiegie/666/main/bxkt.js

# [mitm] 
hostname = api.banxueketang.com
