# 项目名称：iTunes-系列解锁合集
# 更新日期：2026-04-11
# 脚本作者：@ddm1023
# 电报频道：https://raw.githubusercontent.com/chxm1023/Rewrite/main/iTunes.js

# [rewrite_local]
^https?:\/\/buy\.itunes\.apple\.com\/verifyReceipt$ url script-response-body https://raw.githubusercontent.com/chxm1023/Rewrite/main/iTunes.js

# [mitm]
hostname = buy.itunes.apple.com
