#[rewrite_local]
^https:\/\/api-wood\.kaying\.cc\/rest\/user url script-response-body https://raw.githubusercontent.com/gulangyushaonian/Script/refs/heads/main/Script/mgbd.js
#[mitm]
hostname = api-wood.kaying.cc
