# 脚本功能：纳米盒-中小学课本同步辅导提分必备
# 软件版本：13.4
# >纳米盒-中小学课本同步辅导提分必备
^https:\/\/namibox\.com url script-response-body https://raw.githubusercontent.com/WeiGiegie/666/main/namibox.js

# [mitm] 
hostname = namibox.com
