# [rewrite_local]
^https?:\/\/(nicegram\.cloud\/api\/v\d\/(user\/info|unblock-feature\/get-settings)|restore-access\.indream\.app\/restoreAccess|api\.mbrx\.app\/v\d\/purchase\/ios\/transaction) url script-response-body https://raw.githubusercontent.com/chxm1023/Rewrite/main/nicegram.js

# [mitm]
hostname = nicegram.cloud, restore-access.indream.app, api.mbrx.app