# [rewrite_local]
^https:\/\/api\.pingmeapp\.net\/app\/queryBalanceAndBonus url script-request-header https://raw.githubusercontent.com/gulangyushaonian/Script/refs/heads/main/Script/PingMe.js

# [task_local]
31 8,20 * * * https://raw.githubusercontent.com/ZenmoFeiShi/Qx/refs/heads/main/PingMe.js, tag=PingMe签到, enabled=true

# [MITM]
hostname = api.pingmeapp.net
