# [rewrite_local]
# 网上国网接口重写
# 桂林佬的
# ^https?:\/\/api\.wsgw-rewrite\.com\/electricity\/bill\/all url script-analyze-echo-response https://raw.githubusercontent.com/Yuheng0101/X/main/Tasks/95598/95598.js

^https?:\/\/api\.wsgw-rewrite\.com\/electricity\/bill\/all url script-request-header https://raw.githubusercontent.com/Yuheng0101/X/main/Tasks/95598/95598.js


[mitm]
hostname = api.wsgw-rewrite.com
